import os
import os.path

join = os.path.join

Import("env BASE LIBS LIBPATH EXENAME")

env.Program(join(BASE, "bin", EXENAME.format(name="calculator.parser")), Glob("*.c"), LIBPATH=LIBPATH, LIBS=LIBS)

