import os
import os.path

join = os.path.join

Import("env BASE LIBS LIBPATH")

PARSER_FILES = Glob(join("parser", "*.c"))
PTREE_FILES = Glob(join("ptree", "*.c"))
UTIL_FILES = Glob(join("util", "*.c"))

OBJECTS = ["parser_repl.c"]

env.Library(join(BASE, "lib", "libparser.a"), PARSER_FILES + PTREE_FILES)

env.Library(join(BASE, "lib", "libparser_util.a"), UTIL_FILES)

env.Program(join(BASE, "bin", "parser_repl"), OBJECTS, LIBPATH=LIBPATH, LIBS=LIBS)

