import os
import os.path
import sys

join = os.path.join

Import("env BASE LIBS LIBPATH LIBNAME EXENAME")

PARSER_FILES = Glob(join("parser", "*.c"))
PTREE_FILES = Glob(join("ptree", "*.c"))
UTIL_FILES = Glob(join("util", "*.c"))

OBJECTS = ["parser_repl.c"]

PARSER_LIB = join(BASE, "lib", LIBNAME.format(name="parser"))

parser_lib = env.Library(PARSER_LIB, PARSER_FILES + PTREE_FILES)

parser_util_lib = env.Library(join(BASE, "lib", LIBNAME.format(name="parser_util")), UTIL_FILES)

env.Program(join(BASE, "bin", EXENAME.format(name="parser_repl")), OBJECTS, LIBPATH=LIBPATH, LIBS=LIBS)

